import { useMemo, useState } from 'react';
import { ArrowRight, BookOpen, Check, CircleHelp, Compass, Download, FileImage, Gem, Menu, Mountain, Search, Sparkles, Upload, X } from 'lucide-react';

const tags = ['All rocks', 'Igneous', 'Sedimentary', 'Metamorphic', 'Minerals'];
const rocks = [
  ['Granite', 'Igneous', 'Coarse-grained', 'bg-[#9a8772]'], ['Basalt', 'Igneous', 'Fine-grained', 'bg-[#4d5555]'],
  ['Sandstone', 'Sedimentary', 'Clastic', 'bg-[#c59b6f]'], ['Limestone', 'Sedimentary', 'Fossiliferous', 'bg-[#d2c9b6]'],
  ['Slate', 'Metamorphic', 'Foliated', 'bg-[#66757a]'], ['Marble', 'Metamorphic', 'Crystalline', 'bg-[#b8b8ad]'],
  ['Quartz', 'Minerals', 'Hardness 7', 'bg-[#d7d3c6]'], ['Obsidian', 'Igneous', 'Glassy', 'bg-[#30383b]'],
].map(([name, type, detail, color]) => ({ name, type, detail, color }));
const guides = [
  ['A Pocket Guide to Pacific Northwest Rocks', '48 pages · 2.4 MB', 'from-[#d9bd91] via-[#a8835b] to-[#53675e]', 'PNW'],
  ['Reading the Landscape: A Beginner’s Field Guide', '32 pages · 1.8 MB', 'from-[#b6c6b2] via-[#718c73] to-[#40534c]', 'FIELD'],
  ['Minerals Underfoot', '26 pages · 1.2 MB', 'from-[#c9c5b7] via-[#888b7d] to-[#59635e]', 'MINERAL'],
].map(([title, meta, accent, mark]) => ({ title, meta, accent, mark }));

function App() {
  const [activeTag, setActiveTag] = useState('All rocks');
  const [query, setQuery] = useState('');
  const [file, setFile] = useState(null);
  const [dragging, setDragging] = useState(false);
  const filteredRocks = useMemo(() => rocks.filter((rock) => (activeTag === 'All rocks' || rock.type === activeTag) && `${rock.name} ${rock.type} ${rock.detail}`.toLowerCase().includes(query.toLowerCase())), [activeTag, query]);
  const selectFile = (nextFile) => { if (nextFile?.type.startsWith('image/')) setFile(nextFile); };

  return <div className="min-h-screen overflow-x-hidden bg-[#f4f1e9] text-[#27352f]">
    <header className="border-b border-[#d9d7cd] bg-[#f4f1e9]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
      <a href="#top" className="flex items-center gap-2.5"><span className="flex size-9 items-center justify-center rounded-xl bg-[#304b3e] text-[#f5e8ce]"><Gem className="size-5" /></span><span className="font-display text-xl font-bold tracking-tight">fieldstone</span></a>
      <nav className="hidden items-center gap-8 text-sm font-medium text-[#65716b] md:flex"><a className="text-[#304b3e]" href="#identify">Identify a rock</a><a href="#guides" className="transition hover:text-[#304b3e]">Field guides</a><a href="#database" className="transition hover:text-[#304b3e]">Rock database</a></nav>
      <button className="hidden items-center gap-2 rounded-full border border-[#c8c9bd] px-4 py-2 text-sm font-semibold text-[#304b3e] sm:flex"><CircleHelp className="size-4" /> How it works</button><button className="rounded-lg p-2 md:hidden" aria-label="Open navigation"><Menu className="size-5" /></button>
    </div></header>
    <main id="top" className="mx-auto max-w-7xl px-5 pb-20 pt-12 lg:px-8 lg:pt-20">
      <section className="grid items-end gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#c9d5c5] bg-[#e8eee3] px-3 py-1.5 text-xs font-bold uppercase tracking-[0.18em] text-[#47604e]"><Compass className="size-3.5" /> Your field companion</div><h1 className="max-w-3xl font-display text-5xl font-semibold leading-[.98] tracking-[-.045em] text-[#263b31] sm:text-6xl lg:text-7xl">Every stone has a story.<br /><span className="text-[#b17745]">Learn to read it.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#6b736d]">A friendly field guide for curious hikers, collectors, and naturalists. Identify what you find, then take the knowledge with you.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#identify" className="inline-flex items-center gap-2 rounded-full bg-[#304b3e] px-5 py-3.5 text-sm font-bold text-white shadow-lg shadow-[#304b3e]/20 transition hover:-translate-y-0.5 hover:bg-[#243b30]">Launch Rock ID <ArrowRight className="size-4" /></a><a href="#guides" className="inline-flex items-center gap-2 rounded-full border border-[#c8c9bd] bg-white/50 px-5 py-3.5 text-sm font-bold text-[#304b3e] transition hover:bg-white">Explore the guides</a></div><div className="mt-10 flex items-center gap-6 text-sm text-[#68756d]"><span><strong className="text-[#304b3e]">120+</strong> rocks catalogued</span><span className="h-1 w-1 rounded-full bg-[#b17745]" /><span><strong className="text-[#304b3e]">Field-tested</strong> knowledge</span></div></div><div className="relative hidden min-h-[280px] overflow-hidden rounded-[2rem] bg-[#d9e0d3] lg:block"><div className="absolute -right-10 -top-16 size-72 rounded-full border-[24px] border-[#c0cfbd]" /><div className="absolute bottom-[-30px] left-12 size-52 rotate-12 rounded-[40%] bg-[#8a9c8b] shadow-2xl shadow-[#4c6654]/30" /><div className="absolute bottom-[-48px] right-20 size-44 rotate-[-18deg] rounded-[44%] bg-[#b17745]" /><div className="absolute left-20 top-16 size-24 rounded-full bg-[#e4d7ba]" /><div className="absolute inset-x-0 bottom-0 h-16 bg-[#b3c3aa]/60" /><div className="absolute bottom-8 left-8 rounded-full bg-[#f4f1e9]/80 px-3 py-1 text-xs font-bold uppercase tracking-[.18em] text-[#526656]">Look closer</div></div></section>
      <section id="identify" className="mt-20 scroll-mt-6 rounded-[2rem] bg-[#304b3e] p-5 text-white shadow-xl shadow-[#304b3e]/15 sm:p-8 lg:p-10"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-[#d9bd91]"><Sparkles className="size-4" /> Rock ID lab</div><h2 className="font-display text-3xl font-semibold tracking-tight sm:text-4xl">What did you find?</h2><p className="mt-2 max-w-lg text-sm leading-6 text-[#c0cec5]">Upload a clear photo and our field notes will point you in the right direction.</p></div><div className="hidden items-center gap-2 text-xs text-[#b8c9bc] sm:flex"><Check className="size-4 rounded-full bg-[#66816e] p-0.5" /> No account required</div></div><label className={`mt-8 flex min-h-64 cursor-pointer flex-col items-center justify-center rounded-[1.4rem] border border-dashed p-6 text-center transition ${dragging ? 'border-[#e5c99e] bg-[#3d5e4c]' : 'border-[#789180] bg-[#385744] hover:border-[#d9bd91] hover:bg-[#3b604e]'}`} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); selectFile(event.dataTransfer.files?.[0]); }}><input className="hidden" type="file" accept="image/*" onChange={(event) => selectFile(event.target.files?.[0])} />{file ? <><div className="flex size-14 items-center justify-center rounded-2xl bg-[#d9bd91] text-[#304b3e]"><FileImage className="size-7" /></div><p className="mt-4 font-semibold">{file.name}</p><p className="mt-1 text-sm text-[#c0cec5]">Ready to analyze · Click to replace</p><button type="button" onClick={(event) => { event.preventDefault(); setFile(null); }} className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-[#e5c99e] hover:underline">Remove <X className="size-3" /></button></> : <><div className="flex size-14 items-center justify-center rounded-2xl bg-[#d9bd91] text-[#304b3e]"><Upload className="size-7" /></div><p className="mt-4 font-semibold">Drop your rock photo here</p><p className="mt-1 text-sm text-[#c0cec5]">or <span className="font-semibold text-[#e5c99e] underline">browse files</span> · JPG, PNG up to 10 MB</p></>}</label></section>
      <section id="guides" className="mt-20 scroll-mt-6"><div className="flex items-end justify-between gap-4"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.2em] text-[#a76f40]">Take it outside</p><h2 className="font-display text-3xl font-semibold tracking-tight text-[#304b3e] sm:text-4xl">Field guides library</h2><p className="mt-2 text-[#727a73]">Thoughtful notes for your next trail day.</p></div></div><div className="mt-8 grid gap-5 md:grid-cols-3">{guides.map((guide) => <article key={guide.title} className="group overflow-hidden rounded-2xl border border-[#dddcd3] bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className={`relative h-44 bg-gradient-to-br ${guide.accent} p-5`}><div className="absolute inset-0 opacity-20" style={{ backgroundImage: 'radial-gradient(#fff 1px, transparent 1px)', backgroundSize: '12px 12px' }} /><div className="relative flex items-start justify-between"><span className="rounded-full bg-[#f4f1e9]/80 px-2.5 py-1 text-[10px] font-bold tracking-[.18em] text-[#304b3e]">FIELDSTONE EDITION</span><BookOpen className="size-5 text-white/80" /></div><span className="absolute bottom-5 left-5 font-display text-3xl font-bold tracking-tight text-white/80">{guide.mark}</span></div><div className="p-5"><h3 className="min-h-14 font-display text-xl font-semibold leading-tight text-[#304b3e]">{guide.title}</h3><p className="mt-2 text-xs text-[#858b84]">{guide.meta}</p><button className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-full border border-[#c8c9bd] py-2.5 text-sm font-bold text-[#304b3e] transition group-hover:border-[#304b3e] group-hover:bg-[#304b3e] group-hover:text-white"><Download className="size-4" /> View guide</button></div></article>)}</div></section>
      <section id="database" className="mt-20 scroll-mt-6"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.2em] text-[#a76f40]">Know your specimens</p><h2 className="font-display text-3xl font-semibold tracking-tight text-[#304b3e] sm:text-4xl">Rock database</h2><p className="mt-2 text-[#727a73]">Quick filters for your field notes and curious questions.</p></div><div className="flex w-full items-center gap-2 rounded-full border border-[#d2d3c9] bg-white px-4 py-2.5 md:max-w-xs"><Search className="size-4 text-[#89928a]" /><input aria-label="Search rocks" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by name or type" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[#9ba19b]" /></div></div><div className="mt-7 flex flex-wrap gap-2">{tags.map((tag) => <button key={tag} onClick={() => setActiveTag(tag)} className={`rounded-full border px-4 py-2 text-sm font-semibold transition ${activeTag === tag ? 'border-[#304b3e] bg-[#304b3e] text-white' : 'border-[#d2d3c9] bg-white text-[#66726a] hover:border-[#9aae99]'}`}>{tag}</button>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{filteredRocks.map((rock) => <article key={rock.name} className="flex items-center gap-3 rounded-2xl border border-[#deddd4] bg-white p-3.5"><div className={`flex size-12 shrink-0 items-center justify-center rounded-xl ${rock.color} text-white shadow-inner`}><Mountain className="size-6 opacity-80" /></div><div className="min-w-0"><h3 className="font-display text-lg font-semibold text-[#304b3e]">{rock.name}</h3><p className="truncate text-xs text-[#89918a]">{rock.type} · {rock.detail}</p></div></article>)}{filteredRocks.length === 0 && <div className="col-span-full rounded-2xl border border-dashed border-[#c8c9bd] bg-white/50 p-8 text-center text-[#727a73]">No rocks match that search yet.</div>}</div></section>
    </main><footer className="border-t border-[#d9d7cd] bg-[#e8e6dc]"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-7 text-sm text-[#748078] sm:flex-row sm:items-center sm:justify-between lg:px-8"><div className="flex items-center gap-2 font-display font-bold text-[#304b3e]"><Gem className="size-4" /> fieldstone</div><p>Made for the curious, wherever the trail leads.</p><div>Learn · Look · Log</div></div></footer>
  </div>;
}
export default App;
